.TH gfceux 1 "August 10, 2008" "Lukas Sabota"
.SH NAME
GFCE UltraX - A GTK2 graphical front-end for fceux
.SH SYNOPSIS
.B gfceux
.BR [options]
.PP
.SH DESCRIPTION
Gfceux is a graphical front-end for fceux, an advanced Nintendo Entertainment System emulator.  
It allows easy control over various options including input, network, video, and sound.
.SH OPTIONS
.TP
.B --version
Displays the version number of the application
.TP
.B --help 
Displays a help message displaying options
.SH AUTHOR
.TP
Written for Ubuntu/Debian by Lukas Sabota.
