#!/usr/bin/env python
#
# GTK2 GUI for FCE UltraX
#
# Lukas Sabota <ltsmooth42 _at_ gmail _dot_ com>
#
# <http://fceux.com>
try:
	from gfceux import main
except:
	from src import main

app = main.GfceuxApp()


