.TH gfceux 1 "August 2, 2008" "Lukas Sabota"
.SH NAME
GNOME FCE UltraX - A graphical front-end for fceux
.SH SYNOPSIS
.B gfceux
.BR [options]
.PP
.SH DESCRIPTION
GFCE UltraX is a graphical front-end for fceux, an advanced Nintendo Entertainment System emulator.  The program allows easy control over various options including input, network, video, and sound.  It uses the GTK+2 library and optionally GNOMEVFS.
.SH OPTIONS
.TP
.B --version
Displays the version number of the application
.TP
.B --help 
Displays a help message displaying options
.SH AUTHOR
.TP
Written for Ubuntu/Debian by Lukas Sabota.
