.TH gfceu 1 "July 17 2006" "Lukas Sabota"
.SH NAME
GNOME FCE Ultra - A graphical front-end for FCE Ultra
.SH SYNOPSIS
.B gfceu
.BR [options]
.PP
.SH DESCRIPTION
GFCE Ultra is a graphical front-end for FCE Ultra, an advanced Nintendo Entertainment System emulator.  The program allows easy control over various options including input, network, video, and sound.  It uses the GTK+2 library and optionally GNOMEVFS.
.SH OPTIONS
.TP
.B --version
Displays the version number of the application
.TP
.B --help 
Displays a help message displaying options
.SH AUTHOR
.TP
Written for Ubuntu/Debian by Lukas Sabota.
