Import('file_list')
my_list =  Split("""
dface.h
input.cpp
input.h
keyscan.h
main.cpp
main.h
sdl.cpp
sdl.h
sdl-icon.h
sdl-joystick.cpp
sdl-sound.cpp
sdl-throttle.cpp
sdl-video.cpp
sdl-video.h
throttle.h
unix-netplay.cpp
unix-netplay.h
usage.h
""")

# XXX need to deal with opengl configuration and testing at some point
#sdl-opengl.cpp
#sdl-opengl.h


for x in range(len(my_list)):
  my_list[x] = 'drivers/pc/' + my_list[x]
file_list = my_list + file_list
Export('file_list')
