Import('file_list')
my_list =  Split("""
input.cpp
main.cpp
sdl.cpp
sdl-joystick.cpp
sdl-sound.cpp
sdl-throttle.cpp
sdl-video.cpp
unix-netplay.cpp
""")

# XXX need to deal with opengl configuration and testing at some point
#sdl-opengl.cpp
#sdl-opengl.h


for x in range(len(my_list)):
  my_list[x] = 'drivers/pc/' + my_list[x]
file_list = my_list + file_list
Export('file_list')
