//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define GUI_BOT_CLOSE                   1
#define CLOSE_BUTTON                    1
#define BUTTON_CLOSE                    1
#define BTN_CLOSE                       1
#define GUI_BOT_VALUES                  2
#define BTN_CANCEL                      2
#define MENU_OPEN_FILE                  100
#define EDIT_ROMS                       100
#define MENU_CLOSE_FILE                 101
#define IDI_ICON1                       101
#define CB_DISABLE_SPEED_THROTTLING     101
#define IDI_ICON2                       102
#define MENU_RECENT_FILES               102
#define CB_LOAD_FILE_OPEN               102
#define CB_AUTO_HIDE_MENU               104
#define COMBO_PAD1                      104
#define COMBO_PAD2                      105
#define CB_SET_HIGH_PRIORITY            105
#define BTN_PORT1                       106
#define BTN_PORT2                       107
#define IDR_ACCELERATOR1                108
#define MENU_SAVE_STATE                 110
#define CB_ASK_EXIT                     110
#define COMBO_FAM                       110
#define MENU_LOAD_STATE                 111
#define CB_DISABLE_SCREEN_SAVER         111
#define BTN_FAM                         111
#define BTN_AUTO_HOLD                   112
#define BTN_CLEAR_AH                    114
#define LBL_AUTO_HOLD                   115
#define LBL_CLEAR_AH                    116
#define LBL_AUTO_HOLD2                  118
#define LBL_AUTO_HOLD3                  120
#define LBL_AUTO_HOLD4                  122
#define MENU_RECORD_MOVIE               141
#define MENU_REPLAY_MOVIE               142
#define MENU_STOP_MOVIE                 143
#define MENU_RECORD_AVI                 151
#define MENU_STOP_AVI                   152
#define MENU_EXIT                       153
#define MENU_RESET                      200
#define BUTTON_ROMS                     200
#define TXT_PAD1                        200
#define BTN_RESTORE_DEFAULTS            200
#define BTN_CLEAR                       200
#define IDC_EDIT_FILENAME               200
#define IDC_COMBO_FILENAME              200
#define MENU_POWER                      201
#define TXT_PAD2                        201
#define IDC_BUTTON_BROWSEFILE           201
#define IDC_CHECK_READONLY              201
#define MENU_EJECT_DISK                 202
#define TXT_FAM                         202
#define MENU_SWITCH_DISK                203
#define MENU_INSERT_COIN                204
#define MENU_HIDE_MENU                  300
#define CHECK_SCREENSHOT_NAMES          300
#define COMBO_FILTER                    300
#define IDC_EDIT_AUTHORINFO             300
#define IDC_LABEL_LENGTH                300
#define MENU_RUN_IN_BACKGROUND          301
#define IDC_COMBO_RECORDFROM            301
#define IDC_LABEL_FRAMES                301
#define MENU_BACKGROUND_INPUT           302
#define IDC_LABEL_UNDOCOUNT             302
#define MENU_SHOW_STATUS_ICON           303
#define IDC_LABEL_AUTHORINFO            303
#define MENU_ENABLE_REWIND              304
#define IDC_LABEL_ROMUSED               304
#define IDC_LABEL_ROMCHECKSUM           305
#define IDC_LABEL_RECORDEDFROM          306
#define IDC_LABEL_EMULATORUSED          307
#define IDC_LABEL_CURRCHECKSUM          308
#define MENU_GAME_GENIE                 310
#define MENU_PAL                        311
#define MENU_DIRECTORIES                320
#define MENU_INPUT                      321
#define MENU_GUI_OPTIONS                327
#define GUI_BOT_A_1                     1000
#define IDC_EDIT_OFFSET                 1000
#define GUI_BOT_B_1                     1001
#define MW_ADDR00                       1001
#define IDC_EDIT_FROM                   1001
#define GUI_BOT_SELECT_1                1002
#define IDC_CHECK_STOPMOVIE             1002
#define GUI_BOT_START_1                 1003
#define LV_MAPPING                      1003
#define IDC_EDIT_STOPFRAME              1003
#define GUI_BOT_UP_1                    1004
#define MW_ADDR01                       1004
#define GUI_BOT_DOWN_1                  1005
#define GUI_BOT_LEFT_1                  1006
#define GUI_BOT_RIGHT_1                 1007
#define MW_ADDR02                       1007
#define GUI_BOT_A_2                     1008
#define GUI_BOT_END                     1009
#define GUI_BOT_INVALID                 1009
#define GUI_BOT_X                       1010
#define MW_ADDR03                       1010
#define GUI_BOT_TIE1                    1011
#define GUI_BOT_SCORE2                  1011
#define GUI_BOT_TIE2                    1012
#define GUI_BOT_SCORE3                  1012
#define GUI_BOT_TIE3                    1013
#define GUI_BOT_SCORE4                  1013
#define MW_ADDR04                       1013
#define GUI_BOT_SAVE                    1014
#define GUI_BOT_LOAD                    1015
#define GUI_BOT_RUN                     1016
#define MW_ADDR05                       1016
#define GUI_BOT_MAX                     1017
#define GUI_BOT_SCORE1                  1017
#define GUI_BOT_Y                       1018
#define GUI_BOT_KEYS                    1019
#define MW_ADDR06                       1019
#define GUI_BOT_EXTRA                   1020
#define GUI_BOT_BEST                    1021
#define GUI_BOT_Z                       1022
#define MW_ADDR07                       1022
#define GUI_BOT_CHECK                   1023
#define GUI_BOT_COMMENTS                1023
#define GUI_BOT_UPDATE                  1024
#define GUI_BOT_BOTMODE                 1025
#define GUI_BOT_ROMNAME                 1025
#define MW_ADDR08                       1025
#define GUI_BOT_P                       1026
#define GUI_BOT_Q                       1027
#define GUI_BOT_TEST                    1028
#define MW_ADDR09                       1028
#define GUI_BOT_RESET                   1029
#define GUI_BOT_ROLLBACK                1030
#define GUI_BOT_MAXFRAMES               1031
#define MW_ADDR10                       1031
#define GUI_BOT_MAXATTEMPTS             1032
#define GUI_BOT_MAXPARTS                1033
#define GUI_BOT_B_2                     1034
#define MW_ADDR11                       1034
#define GUI_BOT_P1                      1035
#define GUI_BOT_INTERNAL                1035
#define GUI_BOT_CLEAR                   1036
#define GUI_BOT_ATTEMPTS                1037
#define MW_ADDR12                       1037
#define GUI_BOT_SELECT_2                1038
#define GUI_BOT_START_2                 1039
#define GUI_BOT_P2                      1040
#define GUI_BOT_EXTERNAL                1040
#define MW_ADDR13                       1040
#define GUI_BOT_UP_2                    1041
#define GUI_BOT_DOWN_2                  1042
#define GUI_BOT_LEFT_2                  1043
#define MW_ADDR14                       1043
#define GUI_BOT_RIGHT_2                 1044
#define GUI_BOT_SCORE5                  1045
#define GUI_BOT_SCORE6                  1046
#define MW_ADDR15                       1046
#define GUI_BOT_INIT_PART               1047
#define GUI_BOT_INIT_ATTEMPT            1048
#define GUI_BOT_FRAMES                  1049
#define MW_ADDR16                       1049
#define GUI_BOT_BESTRESULT              1050
#define GUI_BOT_LAST                    1051
#define GUI_BOT_U                       1052
#define MW_ADDR17                       1052
#define GUI_BOT_AVGMAX                  1053
#define GUI_BOT_AVGTIE1                 1054
#define MW_ADDR18                       1055
#define GUI_BOT_AVGTIE2                 1056
#define GUI_BOT_AVGTIE3                 1057
#define MW_ADDR19                       1058
#define GUI_BOT_OK                      1061
#define MW_ADDR20                       1061
#define GUI_BOT_ATTEMPT_LAST            1062
#define GUI_BOT_ATTEMPT_BEST            1063
#define GUI_BOT_SCORE_LAST              1064
#define MW_ADDR21                       1064
#define GUI_BOT_SCORE_BEST              1065
#define GUI_BOT_TIE1_LAST               1066
#define GUI_BOT_TIE1_BEST               1067
#define MW_ADDR22                       1067
#define GUI_BOT_TIE2_BEST               1068
#define GUI_BOT_TIE3_BEST               1069
#define GUI_BOT_TIE4_BEST               1070
#define MW_ADDR23                       1070
#define GUI_BOT_TIE5_BEST               1071
#define GUI_BOT_TIE2_LAST               1072
#define GUI_BOT_TIE3_LAST               1073
#define GUI_BOT_TIE4_LAST               1074
#define GUI_BOT_TIE5_LAST               1075
#define GUI_BOT_ATTEMPT_LAST2           1076
#define GUI_BOT_SKIPS                   1077
#define GUI_BOT_FRAMES_LAST             1078
#define GUI_BOT_FRAMES_BEST             1079
#define GUI_BOT_OKS                     1080
#define GUI_BOT_ATTEMPT_PREV            1081
#define GUI_BOT_INVALIDS                1082
#define GUI_BOT_SCORE_PREV              1083
#define GUI_BOT_TIE1_PREV               1084
#define GUI_BOT_TIE2_PREV               1085
#define GUI_BOT_TIE3_PREV               1086
#define GUI_BOT_TIE4_PREV               1087
#define GUI_BOT_TIE5_PREV               1088
#define GUI_BOT_FRAMES_PREV             1089
#define GUI_BOT_PART_LAST               1090
#define GUI_BOT_PART_BEST               1091
#define GUI_BOT_PART_PREV               1092
#define GUI_BOT_LB_PREV                 1093
#define GUI_BOT_TIE5_PREV3              1094
#define GUI_BOT_SLOW                    1095
#define GUI_BOT_FRAMESKIP               1096
#define GUI_BOT_PART_LAST2              1097
#define GUI_BOT_TITLE1                  1098
#define GUI_BOT_TITLE2                  1099
#define GUI_BOT_TITLE3                  1100
#define GUI_BOT_TITLE4                  1101
#define GUI_BOT_TITLE5                  1102
#define GUI_BOT_TITLE6                  1103
#define GUI_BOT_PART_LAST3              1104
#define GUI_BOT_INIT_PART2              1105
#define GUI_BOT_TITLEL1                 1106
#define GUI_BOT_TITLES                  1107
#define GUI_BOT_TITLEL2                 1108
#define GUI_BOT_LOG                     1109
#define GUI_BOT_TITLEL3                 1110
#define GUI_BOT_TITLEL4                 1111
#define GUI_BOT_TITLEL5                 1112
#define GUI_BOT_TITLEL6                 1113
#define GUI_BOT_COUNTERS                1114
#define BTN_ALLOW_LRUD                  1117
#define BTN_PRESET_SET1                 1119
#define BTN_PRESET_SET2                 1120
#define BTN_PRESET_SET3                 1121
#define BTN_PRESET_IMPORT1              1122
#define BTN_PRESET_IMPORT2              1123
#define BTN_PRESET_IMPORT3              1124
#define BTN_PRESET_EXPORT1              1125
#define BTN_PRESET_EXPORT2              1126
#define BTN_PRESET_EXPORT3              1127
#define IDC_LIST1                       1130
#define MENU_NETWORK                    40040
#define MENU_PALETTE                    40041
#define MENU_SOUND                      40042
#define MENU_TIMING                     40043
#define MENU_VIDEO                      40044
#define MENU_HOTKEYS                    40045
#define MENU_ABOUT                      40046
#define MENU_MSGLOG                     40047
#define MENU_CHEATS                     40048
#define MENU_BASIC_BOT                  40049
#define MENU_AUTOFIRE_PATTERN_1         40050
#define MENU_AUTOFIRE_PATTERN_2         40051
#define MENU_AUTOFIRE_PATTERN_3         40052
#define ID_DEBUG_DEBUGGER               40053
#define MENU_AUTOFIRE_PATTERN_4         40053
#define ID_DEBUG_PPUVIEWER              40054
#define MENU_AUTOFIRE_PATTERN_5         40054
#define ID_DEBUG_NAMETABLEVIEWER        40055
#define MENU_AUTOFIRE_PATTERN_6         40055
#define ID_DEBUG_HEXEDITOR              40056
#define MENU_AUTOFIRE_PATTERN_7         40056
#define ID_DEBUG_TRACELOGGER            40057
#define MENU_AUTOFIRE_PATTERN_8         40057
#define MENU_AUTOFIRE_PATTERN_9         40058
#define ID_DEBUG_GAMEGENIEDECODER       40059
#define MENU_AUTOFIRE_PATTERN_10        40059
#define ID_DEBUG_CDLOGGER               40060
#define MENU_AUTOFIRE_PATTERN_11        40060
#define MENU_AUTOFIRE_PATTERN_12        40061
#define MENU_AUTOFIRE_PATTERN_13        40062
#define MENU_AUTOFIRE_PATTERN_14        40063
#define MENU_AUTOFIRE_PATTERN_15        40064
#define MENU_AUTOFIRE_OFFSET_1          40065
#define MENU_AUTOFIRE_OFFSET_2          40066
#define MENU_AUTOFIRE_OFFSET_3          40067
#define MENU_AUTOFIRE_OFFSET_4          40068
#define MENU_AUTOFIRE_OFFSET_5          40069
#define MENU_AUTOFIRE_OFFSET_6          40070
#define MENU_ALTERNATE_AB               40071
#define MENU_EXTERNAL_INPUT             40072
#define MENU_DEBUG                      40073
#define MENU_PPUVIEWER                  40074
#define MENU_NAMETABLEVIEWER            40075
#define MENU_HEXEDITOR                  40076
#define MENU_TRACELOGGER                40077
#define MENU_CDLOGGER                   40078
#define MENU_GAMEGENIEDECODER           40079
#define MENU_DEBUGGER                   40080
#define MENU_MEMORY_WATCH               40081
#define MENU_RAMFILTER                  40082
#define MENU_OPEN                       40083
#define MENU_CLOSE                      40084
#define MENU_SAVEAS                     40085
#define MENU_SAVE                       40086
#define MENU_RECENT                     40087
#define MENU_CLEARTEXT                  40088
#define MENU_LOADSTART                  40089
#define ID_OPTIONS_LOADLASTFILEONSTARTUP 40090
#define ID_OPTIONS_LOADLASTFILE         40091
#define OPTIONS_LOADSTART               40092
#define FILE_OPEN                       40093
#define FILE_CLOSE                      40094
#define FILE_SAVE                       40095
#define FILE_SAVEAS                     40096
#define FILE_RECENT                     40097
#define FILE_CLEARTEXT                  40098
#define ID_HELP_COMMANDS                40099
#define About                           40100
#define ID_HELP_ABOUT                   40101
#define FILE_NEW                        40102
#define MEMW_FILE_NEW                   40103
#define MEMW_FILE_OPEN                  40104
#define MEMW_FILE_SAVE                  40105
#define MEMW_FILE_SAVEAS                40106
#define MEMW_FILE_RECENT                40107
#define MEMW_FILE_CLOSE                 40108
#define MEMW_OPTIONS_LOADSTART          40109
#define MEMW_ID_OPTIONS_LOADLASTFILE    40110
#define MEMW_WCOMMANDS                  40111
#define MEMW_HELP_ABOUT                 40112
#define MEMW_HELP_WCOMMANDS             40113
#define MEMW_OPTIONS_LOADLASTFILE       40114
#define ID_RECENT_                      40115
#define ID_RECENT_1                     40116
#define ID_FILE_RECENT                  40117
#define ID_FILE_RECENT40118             40118
#define ID_ACCELERATOR_CTRL_O           40119
#define MENU_LOG_SOUND                  40120
#define ID_TOOLS_TASEDIT                40123
#define MENU_TASEDIT                    40124
#define MW_ValueLabel2                  65423
#define MW_ValueLabel1                  65426
#define GUI_BOT_DEBUG                   65436
#define GUI_BOT_ERROR                   65438
#define LBL_INPUT_HELP                  65488

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40125
#define _APS_NEXT_CONTROL_VALUE         1131
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
