//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define CLOSE_BUTTON                    1
#define BUTTON_CLOSE                    1
#define BTN_CLOSE                       1
#define BTN_CANCEL                      2
#define MENU_OPEN_FILE                  100
#define EDIT_ROMS                       100
#define LBL_LOG_TEXT                    100
#define LBL_KEY_COMBO                   100
#define LBL_CDLOGGER_CODECOUNT          100
#define CHECK_PALETTE_ENABLED           100
#define LBL_DWBDIALOG_TEXT              100
#define GRP_GAMEPAD1                    100
#define IDC_TRACER_LOG                  100
#define MENU_MV_FILE_SAVE               100
#define IDC_VIDEOCONFIG_MODE            100
#define IDC_ROMPATCHER_OFFSET_BOX       100
#define IDC_ASSEMBLER_HISTORY           100
#define MENU_CLOSE_FILE                 101
#define IDI_ICON1                       101
#define CB_DISABLE_SPEED_THROTTLING     101
#define LBL_CDLOGGER_DATACOUNT          101
#define GRP_PPUVIEW_TABLES              101
#define IDC_NETMOO_STATUS               101
#define GRP_GAMEPAD2                    101
#define IDC_LIST_CHEATS                 101
#define IDC_SCRL_TRACER_LOG             101
#define MENU_MV_FILE_SAVE_AS            101
#define IDC_VIDEOCONFIG_FS              101
#define IDC_DEBUGGER_BP_ADD             101
#define IDC_ROMPATCHER_DOTNES_OFFSET    101
#define IDC_NTVIEW_TABLE_BOX            101
#define IDC_ASSEMBLER_DISASSEMBLY       101
#define IDI_ICON2                       102
#define MENU_RECENT_FILES               102
#define CB_LOAD_FILE_OPEN               102
#define LBL_CDLOGGER_UNDEFCOUNT         102
#define IDC_PPUVIEW_SCANLINE            102
#define IDC_NETMOO_CMD_INPUT            102
#define IDC_CHEAT_ADDR                  102
#define IDC_BTN_START_STOP_LOGGING      102
#define MENU_MV_FILE_LOAD_TBL           102
#define IDC_VIDEOCONFIG_AUTO_FS         102
#define IDC_DEBUGGER_BP_DEL             102
#define IDC_ADDBP_MODE_R                102
#define IDC_ROMPATCHER_OFFSET           102
#define IDC_NTVIEW_SCANLINE             102
#define IDC_ASSEMBLER_PATCH_DISASM      102
#define BTN_CDLOGGER_RESET              103
#define LBL_PPUVIEW_TILE1               103
#define IDC_CHEAT_VAL                   103
#define IDC_RADIO_LOG_LAST              103
#define MENU_MV_FILE_UNLOAD_TBL         103
#define IDC_DEBUGGER_BP_EDIT            103
#define IDC_ADDBP_MODE_W                103
#define IDC_ROMPATCHER_BTN_EDIT         103
#define IDC_NTVIEW_PROPERTIES_LINE_1    103
#define CB_AUTO_HIDE_MENU               104
#define COMBO_PAD1                      104
#define BTN_CDLOGGER_LOAD               104
#define LBL_PPUVIEW_TILE2               104
#define IDC_CHEAT_NAME                  104
#define IDC_RADIO_LOG_TO_FILE           104
#define MENU_MV_FILE_DUMP_RAM           104
#define IDC_VIDEOCONFIG_SYNC_METHOD_WIN 104
#define IDC_DEBUGGER_RUN                104
#define IDC_ADDBP_MODE_X                104
#define IDC_ROMPATCHER_CURRENT_DATA_BOX 104
#define IDC_NTVIEW_PROPERTIES_LINE_2    104
#define COMBO_PAD2                      105
#define CB_SET_HIGH_PRIORITY            105
#define BTN_CDLOGGER_START_PAUSE        105
#define LBL_PPUVIEW_PALETTES            105
#define IDC_CHEAT_VAL_KNOWN             105
#define MENU_MV_FILE_DUMP_PPU           105
#define IDC_VIDEOCONFIG_SYNC_METHOD_FS  105
#define IDC_DEBUGGER_STEP_IN            105
#define IDC_TRACER_LOG_SIZE             105
#define IDC_ADDBP_MEM_CPU               105
#define IDC_ROMPATCHER_CURRENT_DATA     105
#define IDC_NTVIEW_PROPERTIES_LINE_3    105
#define BTN_PORT1                       106
#define BTN_CDLOGGER_SAVE_AS            106
#define IDC_CHEAT_LIST_POSSIBILITIES    106
#define IDC_VIDEOCONFIG_CLIPSIDES       106
#define IDC_DEBUGGER_STEP_OUT           106
#define IDC_ADDBP_MEM_PPU               106
#define IDC_NTVIEW_PROPERTIES_LINE_4    106
#define BTN_PORT2                       107
#define BTN_CDLOGGER_SAVE               107
#define IDC_CHEAT_SCRL_POSSIBILITIES    107
#define IDC_DEBUGGER_STEP_OVER          107
#define IDC_ADDBP_MEM_SPR               107
#define IDC_ROMPATCHER_DISASSEMBLY      107
#define IDR_ACCELERATOR1                108
#define BTN_CDLOGGER_SAVE_STRIPPED      108
#define IDC_CHEAT_VAL_NE_BY             108
#define IDC_DEBUGGER_SEEK_PC            108
#define IDC_CHEAT_VAL_GT_BY             109
#define IDC_DEBUGGER_SEEK_TO            109
#define IDC_ROMPATCHER_PATCH_DATA       109
#define IDC_ADDBP_MODE_X2               109
#define IDC_ADDBP_MODE_F                109
#define IDC_CHEAT_VAL_LT_BY             110
#define MENU_SAVE_STATE                 110
#define CB_ASK_EXIT                     110
#define COMBO_FAM                       110
#define IDB_TE_ARROW                    110
#define IDC_CHECK_LOG_REGISTERS         110
#define IDC_DEBUGGER_BREAK_ON_BAD_OP    110
#define IDC_ROMPATCHER_BTN_APPLY        110
#define MENU_LOAD_STATE                 111
#define CB_DISABLE_SCREEN_SAVER         111
#define BTN_FAM                         111
#define IDC_CHECK_LOG_PROCESSOR_STATUS  111
#define IDC_DEBUGGER_RELOAD_SYMS        111
#define IDC_ROMPATCHER_BTN_SAVE         111
#define BTN_AUTO_HOLD                   112
#define IDC_BTN_LOG_BROWSE              112
#define IDC_DEBUGGER_BOOKMARK_ADD       112
#define IDC_DEBUGGER_BOOKMARK_DEL       113
#define BTN_CLEAR_AH                    114
#define IDC_CHECK_LOG_NEW_INSTRUCTIONS  114
#define IDD_DIALOG1                     114
#define LBL_AUTO_HOLD                   115
#define IDC_CHECK_LOG_NEW_DATA          115
#define IDD_DIALOG2                     115
#define LBL_CLEAR_AH                    116
#define IDC_CHECK_LOG_UPDATE_WINDOW     116
#define CHECK_SOUND_8BIT                122
#define IDD_DIALOG3                     123
#define CHECK_SOUND_GLOBAL_FOCUS        124
#define CHECK_SOUND_ENABLED             126
#define CTL_LATENCY_TRACKBAR            128
#define COMBO_SOUND_QUALITY             129
#define CHECK_SOUND_MUTEFA              130
#define IDC_DISABLE_HW_ACCEL_WIN        130
#define IDC_DISABLE_HW_ACCEL_FS         131
#define MENU_RECORD_MOVIE               141
#define MENU_REPLAY_MOVIE               142
#define MENU_STOP_MOVIE                 143
#define MENU_RECORD_AVI                 151
#define MENU_STOP_AVI                   152
#define MENU_EXIT                       153
#define MENU_RESET                      200
#define BUTTON_ROMS                     200
#define TXT_PAD1                        200
#define BTN_RESTORE_DEFAULTS            200
#define BTN_CLEAR                       200
#define IDC_EDIT_FILENAME               200
#define IDC_COMBO_FILENAME              200
#define BTN_PALETTE_LOAD                200
#define IDC_NETMOO_HOST                 200
#define COMBO_SOUND_RATE                200
#define MENU_MV_EDIT_UNDO               200
#define IDC_VIDEOCONFIG_XRES            200
#define IDC_DEBUGGER_FLAG_N             200
#define IDC_ADDBP_ADDR_START            200
#define MENU_POWER                      201
#define TXT_PAD2                        201
#define IDC_BUTTON_BROWSEFILE           201
#define IDC_CHECK_READONLY              201
#define BTN_PALETTE_RESET               201
#define CTL_PPUVIEW_TRACKBAR            201
#define IDC_NETMOO_PORT                 201
#define MENU_MV_EDIT_COPY               201
#define IDC_VIDEOCONFIG_YRES            201
#define IDC_DEBUGGER_FLAG_V             201
#define IDC_ADDBP_ADDR_END              201
#define IDC_NTVIEW_REFRESH_TRACKBAR     201
#define IDC_ASSEMBLER_APPLY             201
#define MENU_EJECT_DISK                 202
#define TXT_FAM                         202
#define MENU_MV_EDIT_PASTE              202
#define IDC_VIDEOCONFIG_BPP             202
#define IDC_DEBUGGER_FLAG_U             202
#define IDC_ADDBP_CONDITION             202
#define IDC_ASSEMBLER_SAVE              202
#define MENU_SWITCH_DISK                203
#define IDC_NETMOO_NICK                 203
#define IDC_CHEAT_BOX_POSSIBILITIES     203
#define MENU_MV_EDIT_FIND               203
#define IDC_DEBUGGER_FLAG_B             203
#define IDC_ADDBP_NAME                  203
#define IDC_ASSEMBLER_UNDO              203
#define MENU_INSERT_COIN                204
#define COMBO_NETMOO_LOCAL_PLAYERS      204
#define MENU_MV_EDIT_FIND_NEXT          204
#define IDC_DEBUGGER_FLAG_D             204
#define IDC_NETMOO_KEY                  205
#define IDC_DEBUGGER_FLAG_I             205
#define IDC_NETMOO_PASS                 206
#define IDC_DEBUGGER_FLAG_Z             206
#define IDC_DEBUGGER_FLAG_C             207
#define IDC_DEBUGGER_ENABLE_SYMBOLIC    208
#define BTN_NETMOO_CONNECT              250
#define MENU_HIDE_MENU                  300
#define CHECK_SCREENSHOT_NAMES          300
#define COMBO_FILTER                    300
#define IDC_EDIT_AUTHORINFO             300
#define IDC_LABEL_LENGTH                300
#define MENU_MV_VIEW_RAM                300
#define IDC_RADIO_SCALE                 300
#define IDC_DEBUGGER_DISASSEMBLY        300
#define IDC_ASSEMBLER_DEFPUSHBUTTON     300
#define MENU_RUN_IN_BACKGROUND          301
#define IDC_COMBO_RECORDFROM            301
#define IDC_LABEL_FRAMES                301
#define IDC_BTN_CHEAT_ADD               301
#define MENU_MV_VIEW_PPU                301
#define IDC_RADIO_STRETCH               301
#define IDC_DEBUGGER_DISASSEMBLY_VSCR   301
#define MENU_BACKGROUND_INPUT           302
#define IDC_LABEL_UNDOCOUNT             302
#define IDC_BTN_CHEAT_DEL               302
#define MENU_MV_VIEW_ROM                302
#define IDC_VIDEOCONFIG_XSCALE          302
#define IDC_DEBUGGER_BP_LIST            302
#define MENU_SHOW_STATUS_ICON           303
#define IDC_LABEL_AUTHORINFO            303
#define IDC_BTN_CHEAT_UPD               303
#define IDC_VIDEOCONFIG_YSCALE          303
#define MENU_ENABLE_AUTOSAVE            304
#define IDC_LABEL_ROMUSED               304
#define IDC_BTN_CHEAT_RESET             304
#define IDC_VIDEOCONFIG_SCALER_FS       304
#define IDC_DEBUGGER_VAL_A              304
#define IDC_LABEL_ROMCHECKSUM           305
#define IDC_BTN_CHEAT_KNOWN             305
#define IDC_DEBUGGER_VAL_X              305
#define IDC_LABEL_RECORDEDFROM          306
#define IDC_BTN_CHEAT_EQ                306
#define IDC_DEBUGGER_VAL_Y              306
#define IDC_LABEL_EMULATORUSED          307
#define IDC_BTN_CHEAT_NE                307
#define IDC_DEBUGGER_VAL_PC             307
#define IDC_LABEL_CURRCHECKSUM          308
#define IDC_BTN_CHEAT_GT                308
#define IDC_DEBUGGER_STACK_CONTENTS     308
#define IDC_BTN_CHEAT_LT                309
#define IDC_DEBUGGER_VAL_PCSEEK         309
#define MENU_GAME_GENIE                 310
#define IDC_DEBUGGER_VAL_PPU            310
#define MENU_PAL                        311
#define IDC_DEBUGGER_VAL_SPR            311
#define IDC_DEBUGGER_BOOKMARK           312
#define MENU_DIRECTORIES                320
#define MENU_INPUT                      321
#define MENU_GUI_OPTIONS                327
#define CHECK_DISABLE_FOURSCORE         400
#define MENU_MV_BOOKMARKS_RM_ALL        400
#define IDC_WINSIZE_MUL_X               400
#define IDC_CHEAT_CHECK_NE_BY           401
#define IDC_WINSIZE_MUL_Y               401
#define CHECK_ENABLE_FOURSCORE          401
#define IDC_CHEAT_CHECK_GT_BY           402
#define IDC_FORCE_INT_VIDEO_SCALARS     402
#define IDC_CHEAT_CHECK_LT_BY           403
#define IDC_FORCE_ASPECT_CORRECTION     403
#define IDC_DEBUGGER_VAL_S              403
#define IDC_VIDEOCONFIG_ASPECT_X        404
#define IDC_VIDEOCONFIG_ASPECT_Y        405
#define IDC_VIDEOCONFIG_SCALER_WIN      406
#define CTL_TINT_TRACKBAR               500
#define CTL_VOLUME_TRACKBAR             500
#define IDC_SCANLINE_FIRST_NTSC         500
#define IDC_SCANLINE_LAST_NTSC          501
#define CTL_HUE_TRACKBAR                501
#define IDC_DEBUGGER_VAL_SLINE          501
#define IDC_SCANLINE_FIRST_PAL          502
#define IDC_DEBUGGER_ADDR_LINE          502
#define IDC_SCANLINE_LAST_PAL           503
#define IDC_VIDEOCONFIG_NO8LIM          600
#define IDC_DEBUGGER_ROM_PATCHER        602
#define LIST_DEBUGGER_BOOKMARKS         701
#define IDC_EDIT_OFFSET                 1000
#define IDC_GAME_GENIE_CODE             1000
#define IDC_MEMVIEWFIND_WHAT            1000
#define IDC_BOOKMARK_DESCRIPTION        1000
#define MW_ADDR00                       1001
#define IDC_EDIT_FROM                   1001
#define IDC_GAME_GENIE_ADDR             1001
#define IDC_MEMVIEWFIND_TYPE_HEX        1001
#define IDC_NTVIEW_MIRROR_HORIZONTAL    1001
#define IDC_CHECK_STOPMOVIE             1002
#define IDC_GAME_GENIE_COMP             1002
#define IDC_TRACER_STATS                1002
#define IDC_MEMVIEWFIND_TYPE_TEXT       1002
#define IDC_NTVIEW_MIRROR_VERTICAL      1002
#define LV_MAPPING                      1003
#define IDC_EDIT_STOPFRAME              1003
#define IDC_GAME_GENIE_VAL              1003
#define IDC_MEMVIEWFIND_DIR_UP          1003
#define IDC_NTVIEW_MIRROR_FOUR_SCREEN   1003
#define MW_ADDR01                       1004
#define IDC_LIST_GGADDRESSES            1004
#define IDC_MEMVIEWFIND_DIR_DOWN        1004
#define IDC_NTVIEW_MIRROR_SS_TABLE_0    1004
#define IDC_BTN_ADD_TO_CHEATS           1005
#define IDC_MEMVIEWFIND_NEXT            1005
#define IDC_NTVIEW_MIRROR_SS_TABLE_1    1005
#define IDC_NTVIEW_MIRROR_SS_TABLE_2    1006
#define MW_ADDR02                       1007
#define IDC_NTVIEW_MIRROR_SS_TABLE_3    1007
#define IDC_NTVIEW_SHOW_SCROLL_LINES    1008
#define MW_ADDR03                       1010
#define MW_ADDR04                       1013
#define MW_ADDR05                       1016
#define MW_ADDR06                       1019
#define MW_ADDR07                       1022
#define GUI_BOT_BOTMODE                 1025
#define MW_ADDR08                       1025
#define MW_ADDR09                       1028
#define MW_ADDR10                       1031
#define MW_ADDR11                       1034
#define MW_ADDR12                       1037
#define MW_ADDR13                       1040
#define MW_ADDR14                       1043
#define MW_ADDR15                       1046
#define MW_ADDR16                       1049
#define MW_ADDR17                       1052
#define MW_ADDR18                       1055
#define MW_ADDR19                       1058
#define MW_ADDR20                       1061
#define MW_ADDR21                       1064
#define MW_ADDR22                       1067
#define MW_ADDR23                       1070
#define GUI_BOT_PART_LAST               1090
#define BTN_ALLOW_LRUD                  1117
#define BTN_PRESET_SET1                 1119
#define BTN_PRESET_SET2                 1120
#define BTN_PRESET_SET3                 1121
#define BTN_PRESET_IMPORT1              1122
#define BTN_PRESET_IMPORT2              1123
#define BTN_PRESET_IMPORT3              1124
#define BTN_PRESET_EXPORT1              1125
#define BTN_PRESET_EXPORT2              1126
#define BTN_PRESET_EXPORT3              1127
#define IDC_LIST1                       1130
#define IDC_HACKY2                      1131
#define IDC_HACKY1                      1132
#define IDC_BUTTON_METADATA             1132
#define IDC_HACKYEXPORT                 1133
#define IDC_BUTTON1                     1133
#define IDC_BUTTON2                     1134
#define IDC_BUTTON3                     1135
#define IDC_BUTTON4                     1136
#define IDC_RADIO1                      1138
#define IDC_RADIO2                      1139
#define IDC_RADIO3                      1140
#define MEMW_EDIT00FORMULA              1142
#define MEMW_EDIT01FORMULA              1143
#define IDC_BUTTON5                     1144
#define MEMW_EDIT02FORMULA              1144
#define IDC_BUTTON7                     1145
#define MEMW_EDIT03FORMULA              1145
#define IDC_BUTTON8                     1146
#define IDC_EDIT1                       1147
#define IDC_BUTTON9                     1148
#define IDC_LIST2                       1149
#define CHECK_SOUND_MUTETURBO           1179
#define IDC_EDIT_AUTHOR                 1180
#define MEMW_STATIC                     1181
#define MEMW_RESULTS                    1184
#define MEMW_EDIT00RESET                1184
#define MEMW_EDIT01RESET                1185
#define MEMW_EDIT02RESET                1186
#define MEMW_EDIT03RESET                1187
#define MEMW_EDIT00RMADDRESS            1188
#define MEMW_EDIT01RMADDRESS            1189
#define MEMW_EDIT02RMADDRESS            1190
#define MEMW_EDIT03RMADDRESS            1191
#define MEMW_EDIT04RMADDRESS            1192
#define EDIT00_RESULTS                  1193
#define EDIT01_RESULTS                  1194
#define EDIT02_RESULTS                  1195
#define EDIT03_RESULTS                  1196
#define MENU_NETWORK                    40040
#define MENU_PALETTE                    40041
#define MENU_SOUND                      40042
#define MENU_TIMING                     40043
#define MENU_VIDEO                      40044
#define MENU_HOTKEYS                    40045
#define MENU_ABOUT                      40046
#define MENU_MSGLOG                     40047
#define MENU_CHEATS                     40048
#define MENU_BASIC_BOT                  40049
#define MENU_AUTOFIRE_PATTERN_1         40050
#define MENU_AUTOFIRE_PATTERN_2         40051
#define MENU_AUTOFIRE_PATTERN_3         40052
#define ID_DEBUG_DEBUGGER               40053
#define MENU_AUTOFIRE_PATTERN_4         40053
#define ID_DEBUG_PPUVIEWER              40054
#define MENU_AUTOFIRE_PATTERN_5         40054
#define ID_DEBUG_NAMETABLEVIEWER        40055
#define MENU_AUTOFIRE_PATTERN_6         40055
#define ID_DEBUG_HEXEDITOR              40056
#define MENU_AUTOFIRE_PATTERN_7         40056
#define ID_DEBUG_TRACELOGGER            40057
#define MENU_AUTOFIRE_PATTERN_8         40057
#define MENU_AUTOFIRE_PATTERN_9         40058
#define ID_DEBUG_GAMEGENIEDECODER       40059
#define MENU_AUTOFIRE_PATTERN_10        40059
#define ID_DEBUG_CDLOGGER               40060
#define MENU_AUTOFIRE_PATTERN_11        40060
#define MENU_AUTOFIRE_PATTERN_12        40061
#define MENU_AUTOFIRE_PATTERN_13        40062
#define MENU_AUTOFIRE_PATTERN_14        40063
#define MENU_AUTOFIRE_PATTERN_15        40064
#define MENU_AUTOFIRE_OFFSET_1          40065
#define MENU_AUTOFIRE_OFFSET_2          40066
#define MENU_AUTOFIRE_OFFSET_3          40067
#define MENU_AUTOFIRE_OFFSET_4          40068
#define MENU_AUTOFIRE_OFFSET_5          40069
#define MENU_AUTOFIRE_OFFSET_6          40070
#define MENU_ALTERNATE_AB               40071
#define MENU_EXTERNAL_INPUT             40072
#define MENU_PPUVIEWER                  40074
#define MENU_NAMETABLEVIEWER            40075
#define MENU_HEXEDITOR                  40076
#define MENU_TRACELOGGER                40077
#define MENU_CDLOGGER                   40078
#define MENU_GAMEGENIEDECODER           40079
#define MENU_DEBUGGER                   40080
#define MENU_MEMORY_WATCH               40081
#define MENU_RAMFILTER                  40082
#define MEMW_FILE_NEW                   40103
#define MEMW_FILE_OPEN                  40104
#define MEMW_FILE_SAVE                  40105
#define MEMW_FILE_SAVEAS                40106
#define MEMW_FILE_RECENT                40107
#define MEMW_FILE_CLOSE                 40108
#define MEMW_OPTIONS_LOADSTART          40109
#define MEMW_HELP_WCOMMANDS             40113
#define MEMW_OPTIONS_LOADLASTFILE       40114
#define ID_FILE_RECENT                  40117
#define MENU_RECORD_WAV                 40120
#define MENU_STOP_WAV                   40121
#define MENU_TASEDIT                    40124
#define MENU_PAUSEAFTERPLAYBACK         40126
#define ACCEL_CTRL_O                    40130
#define ACCEL_CTRL_E                    40131
#define ACCEL_CTRL_W                    40132
#define ACCEL_CTRL_S                    40134
#define ACCEL_CTRL_SHIFT_S              40135
#define ACCEL_CTRL_N                    40136
#define ACCEL_CTRL_C                    40138
#define MENU_HELP                       40140
#define ID_FILE_OOADFM2                 40141
#define ID_FILE_OPENFM2                 40142
#define ID_FILE_SAVEFM2                 40143
#define ID_TWEAKS_DISPLAYBG             40144
#define ID_TWEAKS_DISPLAYOBJ            40145
#define ID_                             40146
#define MENU_DISPLAY_BG                 40147
#define MENU_DISPLAY_OBJ                40148
#define ID_FILE_CONVERTMOVIE            40149
#define MENU_CONVERT_MOVIE              40150
#define ID_STRAY_INSERTFRAMES           40151
#define MENU_INSERTFRAMES               40152
#define ID_SELECTED_INSERTFRAME         40153
#define ID_SELECTED_DELETEFRAME         40154
#define MENU_DELETEFRAME                40155
#define MENU_DELETEFRAMES               40156
#define MENU_STRAY_INSERTFRAMES         40157
#define ID_TOOLS_TEXTHOOKER             40158
#define ID_Menu                         40159
#define ID_STRAY_TRUNCATE               40160
#define ID_SELECTED_BRANCH              40161
#define ID_SELECTED_INSERTMARKER        40162
#define ID_SELECTED_CREATEMACRO         40163
#define ID_EDIT                         40164
#define ID_EDIT_COPY40165               40165
#define ID_EDIT_PASTE40166              40166
#define ID_EDIT_CUT40167                40167
#define ID_EDIT_COPYTONEW               40168
#define ID_EDIT_DELETE                  40169
#define ID_HELP_TASEDITHELP             40170
#define ID_FILE_NEWPROJECTCTRL          40171
#define ID_FILE_SAVEPROJECT             40172
#define ID_FILE_SAVEAS                  40173
#define ID_FILE_CLOSECTRL               40174
#define ID_Menu40175                    40175
#define ID_Menu40176                    40176
#define ID_EDIT_TRUNCATE                40177
#define ID_FILE_IMPORTFM2               40178
#define ID_FILE_NEWPROJECT              40179
#define ID_FILE_OPEN_PROJECT            40180
#define ID_FILE_OPENPROJECT             40181
#define ID_FILE_SAVEPROJECTAS           40182
#define ID_FILE_EXPORTFM2               40183
#define ACCEL_CTRL_X                    40184
#define ID_EDIT_ADDMARKER               40186
#define ID_EDIT_REMOVE_MARKER           40187
#define ID_TASEDIT_CUT                  40188
#define ID_TASEDIT_COPY                 40189
#define ID_TASEDIT_COPYTONEW            40190
#define ID_TASEDIT_PASTE                40191
#define ID_TASEDIT_DELETE               40192
#define ID_TASEDIT_FILE_CLOSE           40193
#define ID_TASEDIT_PASTETONEW           40194
#define ACCEL_CTRL_V                    40195
#define ACCEL_CTRL_SHIFT_V              40196
#define ACCEL_CTRL_DELETE               40197
#define ID_ACCEL_CTRL_T                 40198
#define ACCEL_CTRL_T                    40198
#define ACCEL_CTRL_B                    40199
#define ID_CONTEXT_SELECTED_TRUNCATE    40200
#define ID_CONTEXT_STRAY_TRUNCATE       40201
#define ID_VIEW                         40202
#define MENU_CONTEXT_STRAY_INSERTFRAMES 40203
#define ID_CONTEXT_SELECTED_INSERTFRAMES 40204
#define ID_CONTEXT_SELECTED_DELETEFRAMES 40205
#define ID_SELECTED_REMOVEMARKER        40206
#define ID_CONTEXT_SELECTED_PASTETONEW  40207
#define ID_CONTEXT_SELECTED_ADDMARKER   40208
#define ID_CONTEXT_SELECTED_REMOVEMARKER 40209
#define ID_CONTEXT_SELECTED_BRANCH      40210
#define ID_EDIT_BRANCHCTRL              40211
#define ID_EDIT_BRANCH                  40212
#define ID_EDIT_SELECTALL               40214
#define ID_EDIT_REMOVEMARKER            40215
#define ID_FILE_CLOSECTRL40216          40216
#define ID_MEMWVIEW_FILE_CLOSE          40217
#define ID_FILE_CLOSE40218              40218
#define MENU_BASIC_BOT2                 40220
#define ID_FILE_RUNLUASCRIPT            40229
#define ID_FILE_STOPLUASCRIPT           40230
#define ID_CONFIG_DISPLAY               40231
#define ID_DISPLAY_INPUTDISPLAY         40232
#define ID_DISPLAY_LAGCOUNTER           40233
#define FCUE_DISPLAY_INPUTDISPLAY       40234
#define FCEU_DISPLAY_LAGCOUNTER         40235
#define MENU_DISPLAY_INPUTDISPLAY       40236
#define MENU_DISPLAY_LAGCOUNTER         40237
#define ID_DISPLAY_FRAMEADV             40238
#define MENU_DISPLAY_FA_LAGSKIP         40239
#define ID_DISPLAY_INPUTDISPLAY40240    40240
#define ID_LAGCOUNTER_OFF               40241
#define ID_LAGCOUNTER_1PLAYER           40242
#define ID_LAGCOUNTER_2PLAYER           40243
#define ID_LAGCOUNTER_4PLAYER           40244
#define ID_DISPLAY_LAGCOUNTER40245      40245
#define MENU_INPUTDISPLAY_OFF           40246
#define MENU_INPUTDISPLAY_1P            40247
#define MENU_INPUTDISPLAY_2P            40248
#define MENU_INPUTDISPLAY_4P            40249
#define MENU_INPUTDISPLAY_0             40250
#define MENU_INPUTDISPLAY_1             40251
#define MENU_INPUTDISPLAY_2             40252
#define MENU_INPUTDISPLAY_4             40253
#define ID_DISPLAY_FRAMECOUNTER         40254
#define ID_CONFIG_BINDSAVESTATESTOMOVIE 40255
#define MENU_CONFIG_BINDSAVES           40256
#define IDC_DEBUGGER_ICONTRAY           55535
#define MW_ValueLabel2                  65423
#define MW_ValueLabel1                  65426

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        124
#define _APS_NEXT_COMMAND_VALUE         40257
#define _APS_NEXT_CONTROL_VALUE         1187
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
