//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define GUI_BOT_CLOSE                   1
#define GUI_BOT_VALUES                  2
#define IDI_ICON1                       101
#define IDI_ICON2                       102
#define GUI_BOT_A_1                     1000
#define GUI_BOT_B_1                     1001
#define GUI_BOT_SELECT_1                1002
#define GUI_BOT_START_1                 1003
#define GUI_BOT_UP_1                    1004
#define GUI_BOT_DOWN_1                  1005
#define GUI_BOT_LEFT_1                  1006
#define GUI_BOT_RIGHT_1                 1007
#define GUI_BOT_A_2                     1008
#define GUI_BOT_END                     1009
#define GUI_BOT_INVALID                 1009
#define GUI_BOT_X                       1010
#define GUI_BOT_TIE1                    1011
#define GUI_BOT_TIE2                    1012
#define GUI_BOT_TIE3                    1013
#define GUI_BOT_SAVE                    1014
#define GUI_BOT_LOAD                    1015
#define GUI_BOT_RUN                     1016
#define GUI_BOT_MAX                     1017
#define GUI_BOT_SCORE                   1017
#define GUI_BOT_Y                       1018
#define GUI_BOT_KEYS                    1019
#define GUI_BOT_EXTRA                   1020
#define GUI_BOT_BEST                    1021
#define GUI_BOT_Z                       1022
#define GUI_BOT_CHECK                   1023
#define GUI_BOT_COMMENTS                1023
#define GUI_BOT_UPDATE                  1024
#define GUI_BOT_BOTMODE                 1025
#define GUI_BOT_P                       1026
#define GUI_BOT_Q                       1027
#define GUI_BOT_TEST                    1028
#define GUI_BOT_RESET                   1029
#define GUI_BOT_ROLLBACK                1030
#define GUI_BOT_MAXFRAMES               1031
#define GUI_BOT_MAXATTEMPTS             1032
#define GUI_BOT_MAXPARTS                1033
#define GUI_BOT_B_2                     1034
#define GUI_BOT_P1                      1035
#define GUI_BOT_INTERNAL                1035
#define GUI_BOT_CLEAR                   1036
#define GUI_BOT_ATTEMPTS                1037
#define GUI_BOT_SELECT_2                1038
#define GUI_BOT_START_2                 1039
#define GUI_BOT_P2                      1040
#define GUI_BOT_EXTERNAL                1040
#define GUI_BOT_UP_2                    1041
#define GUI_BOT_DOWN_2                  1042
#define GUI_BOT_LEFT_2                  1043
#define GUI_BOT_RIGHT_2                 1044
#define GUI_BOT_TIE4                    1045
#define GUI_BOT_TIE5                    1046
#define GUI_BOT_FRAMES                  1049
#define GUI_BOT_BESTRESULT              1050
#define GUI_BOT_LAST                    1051
#define GUI_BOT_U                       1052
#define GUI_BOT_AVGMAX                  1053
#define GUI_BOT_AVGTIE1                 1054
#define GUI_BOT_AVGTIE2                 1056
#define GUI_BOT_AVGTIE3                 1057
#define GUI_BOT_OK                      1061
#define GUI_BOT_ATTEMPT_LAST            1062
#define GUI_BOT_ATTEMPT_BEST            1063
#define GUI_BOT_SCORE_LAST              1064
#define GUI_BOT_SCORE_BEST              1065
#define GUI_BOT_TIE1_LAST               1066
#define GUI_BOT_TIE1_BEST               1067
#define GUI_BOT_TIE2_BEST               1068
#define GUI_BOT_TIE3_BEST               1069
#define GUI_BOT_TIE4_BEST               1070
#define GUI_BOT_TIE5_BEST               1071
#define GUI_BOT_TIE2_LAST               1072
#define GUI_BOT_TIE3_LAST               1073
#define GUI_BOT_TIE4_LAST               1074
#define GUI_BOT_TIE5_LAST               1075
#define GUI_BOT_SKIPS                   1077
#define GUI_BOT_FRAMES_LAST             1078
#define GUI_BOT_FRAMES_BEST             1079
#define GUI_BOT_OKS                     1080
#define GUI_BOT_ATTEMPT_PREV            1081
#define GUI_BOT_INVALIDS                1082
#define GUI_BOT_SCORE_PREV              1083
#define GUI_BOT_TIE1_PREV               1084
#define GUI_BOT_TIE2_PREV               1085
#define GUI_BOT_TIE3_PREV               1086
#define GUI_BOT_TIE4_PREV               1087
#define GUI_BOT_TIE5_PREV               1088
#define GUI_BOT_FRAMES_PREV             1089
#define GUI_BOT_PART_LAST               1090
#define GUI_BOT_PART_BEST               1091
#define GUI_BOT_PART_PREV               1092
#define GUI_BOT_LB_PREV                 1093
#define GUI_BOT_TIE5_PREV3              1094
#define GUI_BOT_SLOW                    1095
#define GUI_BOT_FRAMESKIP               1096
#define ID_DEBUG_DEBUGGER               40053
#define ID_DEBUG_PPUVIEWER              40054
#define ID_DEBUG_NAMETABLEVIEWER        40055
#define ID_DEBUG_HEXEDITOR              40056
#define ID_DEBUG_TRACELOGGER            40057
#define ID_DEBUG_GAMEGENIEDECODER       40059
#define ID_DEBUG_CDLOGGER               40060
#define GUI_BOT_DEBUG                   65436
#define GUI_BOT_ERROR                   65438

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
