import glob                                                                                   
source_list = glob.glob('*.cpp') + glob.glob('*.c')

for x in range(len(source_list)):
  source_list[x] = 'mappers/' + source_list[x]
Return('source_list')
