import glob                                                                                   
source_list = glob.glob('*.cpp')

for x in range(len(source_list)):
  source_list[x] = 'utils/' + source_list[x]
Return('source_list')
