.\" (C) Copyright 2012 Joe Nahmias <jello@debian.org>
.Dd November 19, 2014
.Dt FCEUX-NET-SERVER 6
.Os
.Sh NAME
.Nm fceux-net-server
.Nd FCEUX game server
.Sh SYNOPSIS
.Nm fceux-net-server
.Op Cm options
.Sh DESCRIPTION
This manual page documents briefly the
.Nm
command.
.Pp
.Nm
is the game server for multiplayer use of the
.Xr fceux 6
family of NES emulators.
This server will first look in
.Pa /etc/fceux-server.conf
for options.
If that file does not exist, it will use the defaults given here.
Any argument given directly will override any default values.
.Sh OPTIONS
The options are as follows:
.Bl -tag -width Ds
.It Fl h , Fl -help
Displays a help message.
.It Fl v , Fl -version
Displays the version number and quits.
.It Fl p Ar port , Fl -port Ar port
Starts server on given port; the default is 4046.
.It Fl w Ar password , Fl -password Ar password
Specifies a password for entry.
.It Fl m Ar num , Fl -maxclients Ar num
Specifies the maximum number of clients allowed to access the server;
the default is 100.
.It Fl t Ar timeout , Fl -timeout Ar timeout
Specifies the number of seconds before the server times out; the default is 5.
.It Fl f Ar divisor , Fl -framedivisor Ar divisor
Specifies frame divisor, which controls the number of updates sent to client;
calculated as: 60 \(di framedivisor = updates per second.
The default is 1.
.It Fl c Ar file , Fl -configfile Ar file
Loads the given configuration file.
The default is
.Pa /etc/fceux-server.conf .
.El
.Sh SEE ALSO
.Xr fceux 6
.Pp
.Lk http://fceux.com/ "The FCEUX homepage" .
.Sh AUTHORS
.An -nosplit
This manual page was written by
.An Joe Nahmias  Aq Mt jello@debian.org
for the Debian GNU/Linux system (but may be used by others).
